import "./globals.css";
import Header from "./header";
import {SearchContextProvider} from "./context/SearchContext";



export const metadata = {
  title: "SuperStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <SearchContextProvider>
        <Header />
        {children}
        </SearchContextProvider>
        </body>
    </html>
  );
}
